### ISSUE TITLE
Capability to specify feedrate within motion commands.

### ISSUE THREAD

**Issue by RobWks** [jhardin4/APE#2]
I think in the end it would be better to assign specific values for the federate instead of a multiplier. The multiplication of the calibrated feedrate can be easily handled separately and would be simpler than having to find the correct multiplier if a specific value is needed. It should default to the calibrated feedrate if no feedrate is provided.

Thanks!

**Comment by jhardin4** [comment]
I went ahead and added both.  I am also adding an examples folder.  Take a look at the my branch or main.  Look are toolpath_print to see how it is implemented.

**Comment by RobWks** [comment]
This works perfectly!
