### ISSUE TITLE
An example of specifying a travel move in the toolpath generator.

### ISSUE THREAD

**Issue by RobWks** [jhardin4/APE#4]
For the last part of the test pattern, the nozzle is being driven through a filament without extruding. How can I  specify the motion that the nozzle should be moving without it being a print move? I could set the pressure to 0.

Thanks!

**Comment by jhardin4** [comment]
that one is pretty easy.  Just set the material to <materialname>slide.  If you look at the ChangeMat slide then you can see how it is handled when the adding non-printing motions into sequence with others.

**Comment by RobWks** [comment]
Got it, i'll integrate that into the mecode export_APE function.
